#! /bin/sh

case "$1" in
    start)
	printf "Starting nqptp: "
	start-stop-daemon -S -q -b --exec /usr/bin/nqptp
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping shairport-sync: "
	start-stop-daemon -K -q --exec /usr/bin/nqptp \
		-p /var/run/nqptp/nqptp.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
